//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamReport
    {
        public int report_id { get; set; }
        public Nullable<int> attempt_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public int level_number { get; set; }
        public int total_marks { get; set; }
        public int passing_marks { get; set; }
        public int score { get; set; }
        public bool is_passed { get; set; }
        public int total_time { get; set; }
        public int time_taken { get; set; }
    
        public virtual cours cours { get; set; }
        public virtual ExamAttempt ExamAttempt { get; set; }
        public virtual User User { get; set; }
    }
}
