//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamAttempt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamAttempt()
        {
            this.ExamReports = new HashSet<ExamReport>();
            this.UserAnswers = new HashSet<UserAnswer>();
        }
    
        public int attempt_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public int level_number { get; set; }
        public int total_questions { get; set; }
        public int correct_answers { get; set; }
        public int score { get; set; }
        public int total_time { get; set; }
        public int time_taken { get; set; }
        public bool is_passed { get; set; }
    
        public virtual cours cours { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamReport> ExamReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAnswer> UserAnswers { get; set; }
    }
}
