//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentProgress
    {
        public int progress_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<int> highest_level_passed { get; set; }
        public Nullable<bool> is_completed { get; set; }
    
        public virtual cours cours { get; set; }
        public virtual User User { get; set; }
    }
}
