//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOTP
    {
        public int otp_id { get; set; }
        public int user_id { get; set; }
        public string otp { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<bool> is_used { get; set; }
    
        public virtual User User { get; set; }
    }
}
