//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswer
    {
        public int answer_id { get; set; }
        public Nullable<int> attempt_id { get; set; }
        public Nullable<int> question_id { get; set; }
        public string selected_option { get; set; }
        public bool is_correct { get; set; }
    
        public virtual ExamAttempt ExamAttempt { get; set; }
        public virtual Question Question { get; set; }
    }
}
